services:

 postgresql:
  container_name: postgresql
  build: postgresql/
  environment:
   POSTGRES_MULTIPLE_DATABASES: '"django-enterpoll"'
   POSTGRES_HOST_AUTH_METHOD: trust
  restart: always
  volumes:
   - postgresql_data:/var/lib/postgresql/data/
#  healthcheck:
#   test: pg_isready -h postgresql -p 5432 -d postgres -U postgres
#   start_period: 10s
#   start_interval: 1s

 django-enterpoll:
  container_name: django-enterpoll
  build: django/enterpoll/
  environment:
   CONTAINER_NAME: django-enterpoll
   POSTGRESQL_HOST: postgresql
   POSTGRESQL_PORT: 5432
   POSTGRESQL_NAME: django-enterpoll
   POSTGRESQL_USER: django-enterpoll
   REDIS_HOST: redis
  restart: always
  volumes:
   - static:/django/enterpoll/mysite/static/
  develop:
   watch:
    - action: rebuild
      path: django/enterpoll/
      target: /django/enterpoll/
#  healthcheck:
#   test: curl -f http://django:80/ || exit 1
#   start_period: 10s
#   start_interval: 1s
#  depends_on:
#   postgresql:
#    condition: service_healthy
#    restart: true

 nginx:
  container_name: nginx
  build: nginx/
  ports:
   - '80:80'
  restart: always
  volumes:
   - static:/nginx/static/
  develop:
   watch:
    - action: rebuild
      path: nginx/
      target: /etc/nginx/
#  depends_on:
#   django:
#    condition: service_healthy
#    restart: true
#  deploy:
#   resources:
#    limits:
#     memory: 1G

 redis:
  container_name: redis
  build: redis/
  restart: always
  develop:
   watch:
    - action: rebuild
      path: redis/
      target: /usr/local/etc/redis/

volumes:
 postgresql_data:
 static:
