# Generated by Django 5.1.4 on 2025-02-07 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_rating_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(fields=('poll', 'text'), name='unique_choice'),
        ),
        migrations.AddConstraint(
            model_name='poll',
            constraint=models.UniqueConstraint(fields=('title', 'user'), name='unique_poll'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'poll'), name='unique_rating'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'poll'), name='unique_vote'),
        ),
    ]
