# Generated by Django 5.1.4 on 2025-02-02 23:08

import custom_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_comment_user_alter_rating_user_alter_vote_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[custom_validators.forbidden_words], verbose_name='Описание'),
        ),
    ]
