# Generated by Django 5.1.4 on 2025-02-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_comment_user_alter_rating_user_alter_vote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
