# Generated by Django 5.1.4 on 2025-02-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_poll_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='is_published',
        ),
    ]
